# Generated by Django 2.0.4 on 2018-04-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0005_auto_20180426_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(blank=True),
        ),
    ]
